query getPrevIssues(
  $repoOwner: String!
  $repoName: String!
  $fetchIssueCount: Int = 5
  $fetchCommentCount: Int = 5
  $startCursor: String
) {
  repository(owner: $repoOwner, name: $repoName) {
    name
    description
    issues(
      orderBy: { field: CREATED_AT, direction: DESC }
      last: $fetchIssueCount
      before: $startCursor
    ) {
      totalCount
      pageInfo {
        startCursor
        endCursor
        hasPreviousPage
        hasNextPage
      }
      nodes {
        author {
          avatarUrl
          login
          resourcePath
          url
        }
        title
        body
        createdAt
        publishedAt
        updatedAt
        url
        comments(first: $fetchCommentCount) {
          pageInfo {
            endCursor
            hasNextPage
          }
          nodes {
            author {
              avatarUrl
              login
              resourcePath
              url
            }
            body
          }
        }
      }
    }
  }
}
