query getPrevIssues(
  $repoOwner: String!
  $repoName: String!
  $fetchIssueCount: Int = 5
  $startCursor: String
) {
  repository(owner: $repoOwner, name: $repoName) {
    name
    description
    issues(
      orderBy: { field: CREATED_AT, direction: DESC }
      last: $fetchIssueCount
      before: $startCursor
    ) {
      totalCount
      pageInfo {
        startCursor
        endCursor
        hasPreviousPage
        hasNextPage
      }
      nodes {
        author {
          avatarUrl
          login
          resourcePath
          url
        }
        id
        number
        title
        body
        createdAt
        updatedAt
        url
      }
    }
  }
}
